#+TITLE: Práctica 1 - GEMM
#+AUTHOR: Adrián Arroyo Calle
#+EMAIL: adrian.arroyo.calle@uva.es
#+DATE: Curso 2023-2024
#+OPTIONS: toc:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[spanish]{babel}

* Objetivo

Desarrollar una implementación paralela eficiente del producto matriz-matriz generalizado (GEMM) usando Julia.

Se define la operación GEMM como:

$$
C = C + AB
$$

donde $C \in \mathbb{R}^{m \times n}$, $A \in \mathbb{R}^{m \times k}$, $B \in \mathbb{R}^{k \times n}$ son matrices con valores reales.

Para ello deberá implementarse:

** GEMM secuencial

Un GEMM secuencial basado en tres bucles.

#+begin_src
procedure GEMM (A, B, C)
  input: A M*K-matrix, B K*N-matrix, C M*K-matrix
  output: C M*N-matrix

  for ( i = 0; i < M; i++ )
    for ( j = 0; j < N; j++ )
      for ( k = 0; k < K; k++ )
        C[i,j] = C[i,j] + A[i,k] * B[k,j]
end GEMM
#+end_src

** Validador

Simplemente ejecuta una GEMM secuencial sobre las matrices A, B, C dadas
y comprueba que el resultado coincida con el almacenado en otra matriz resultado C'
dada. Esta comprobación debe hacerse sumando las diferencias entre ambas en valor absoluto:

$$
\sum_{i=1}^{m}\sum_{j=1}^{n} \mid C_{i,j} - C'_{i_j} \mid
$$

El validador se utilizará para verificar el resultado
de las ejecuciones paralelas.

** GEMM paralela

En la que el trabajo de uno (o varios) bucles se reparta entre los hilos
que intervienen en la ejecución.

* Trabajo a realizar

1. Implementar la GEMM secuencial y el validador descritos en la sección anterior.
2. Implementar 3 versiones válidas (el resultado es numéricamente correcto) de la GEMM paralelizada.
3. Justificar un caso en el que un determinado bucle de la GEMM no pueda ser paralelizado (el resultado sería numericamente incorrecto).
4. Realizar un análisis de escalabilidad (fuerte o débil) describiendo las dimensiones de
   las matrices utilizadas en dicho análisis, así como la cantidad de hilos utilizados en las
   pruebas y el número de repeticiones realizadas de cada ejecución. Se presentará tanto
   una tabla reflejando los tiempos de ejecución medidos (el asociado a cada repetición
   y la media), como una gráfica que ilustre la escalabilidad que se observa.

   *Observación 1*: Se recomienda, al menos, repetir cada medida cinco veces (anotando
   todos los tiempos obtenidos en la tabla).

   *Observación 2*: En el caso de que se detecte algún outlier, debe eliminarse antes de hacer
   el cálculo de la media, marcándolo como outlier en la tabla.

   *Observación 3*: Basta con medir el tiempo de la región paralela (tp), no es necesario medir
   también el tiempo total de ejecución.

   *Observación 4*: Las matrices utilizadas en el proceso de experimentación deben ser su-
   ficientemente grandes como para que se llegue a observar una mejora del tiempo de
   ejecución al usar la implementación paralela (no hay que tener miedo a probar productos
   de matrices 1000x1000, 2000x2000...). Tras validar con matrices pequeñas (100x100, por
   ejemplo) que el resultado derivado de la ejecución paralela es correcto, puede "comen-
   tarse" la llamada al validador en el código para no "perder el tiempo" con comprobaciones
   innecesarias.
5. Incluir en la tabla realizada en el apartado anterior una columna donde se indiquen el
   *speedup* y la *eficiencia* (según la media de tiempo calculada).

   La tabla podría acabar siendo algo así:

   | Cantidad de hilos | TP1 | TP2 | TP3 | TP4 | TP5 | MEDIA | Speedup | Eficiencia |
   |-------------------+-----+-----+-----+-----+-----+-------+---------+------------|
   |    1 (secuencial) |     |     |     |     |     |       |         |            |
   |                 2 |     |     |     |     |     |       |         |            |
   |                 4 |     |     |     |     |     |       |         |            |
   |                 6 |     |     |     |     |     |       |         |            |
   |               ... |     |     |     |     |     |       |         |            |
6. Escribir una pequeña reflexión a modo de conclusión del trabajo realizado (uno o dos
   párrafos).

* Entrega

La práctica deberá entregarse antes de TODO

Se deberán presentar las distintas implementaciones (en forma de código Julia con extensión .jl) y
un documento breve incluyendo los resultados derivados de la evaluación (tabla y gráficas), así como
las reflexiones finales.
